name: context-matters
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - networkx
  - matplotlib
  - pandas
  - pytorch=1.8.1
  - pytorch-lightning
  - pip:
    - -e kglib
    - -e grakn-pytorch-geometric
    - -e graph-dash-app
    - dash
    - dash-cytoscape
    - pytest
    - grakn-client==2.0.0
    - torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html
    - torch-sparse -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html
    - torch-cluster -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html
    - torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html
    - torch-geometric