name: context-is-everything
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pip
  - networkx
  - matplotlib
  - pandas
  - pytorch=1.7.0
  - pytorch-lightning
  - pip:
    - -e kglib
    - -e grakn-pytorch-geometric
    - -e graph-dash-app
    - dash
    - dash-cytoscape
    - pytest
    - grakn-client==2.0.0-alpha-8
    - torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
    - torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
    - torch-cluster -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
    - torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
    - torch-geometric